import type { UpgradeDef } from "./upgradeTypes";

export const UPGRADE_DEFS: UpgradeDef[] = [
  {
    id: "boost_regen_up",
    name: "Boost Regen +25%",
    description: "Boost regen rate +25% while not thrusting.",
    tags: ["boost"],
    rarity: "common",
    stackable: true,
    effect: { type: "stat_mult", stat: "boostRegenPerSec", multiplier: 1.25 },
  },
  {
    id: "thrust_power_up",
    name: "Thrust Power +15%",
    description: "Thrust acceleration increased by 15%.",
    tags: ["boost", "thrust"],
    rarity: "common",
    stackable: true,
    effect: { type: "stat_mult", stat: "thrustAccel", multiplier: 1.15 },
  },
  {
    id: "drag_debuff_down",
    name: "Drag Resist",
    description: "Enemy drag debuff duration reduced by 20%.",
    tags: ["defense"],
    rarity: "common",
    stackable: true,
    effect: { type: "stat_mult", stat: "dragDebuffSec", multiplier: 0.8 },
  },
  {
    id: "contact_loss_down",
    name: "Reinforced Hull",
    description: "Retain 10% more speed on enemy contact.",
    tags: ["defense"],
    rarity: "rare",
    stackable: true,
    effect: { type: "stat_mult", stat: "contactSpeedRetain", multiplier: 1.1 },
  },
  {
    id: "cannon_cooldown_down",
    name: "Rapid Fire",
    description: "Auto-cannon fires 12% faster.",
    tags: ["weapon"],
    rarity: "common",
    stackable: true,
    effect: { type: "weapon_mod", weaponTag: "auto", mods: { cooldownMult: 0.88 } },
  },
  {
    id: "cannon_damage_up",
    name: "Armor Piercing",
    description: "Auto-cannon deals +2 damage per shot.",
    tags: ["weapon"],
    rarity: "common",
    stackable: true,
    effect: { type: "weapon_mod", weaponTag: "auto", mods: { damageAdd: 2 } },
  },
  {
    id: "extra_shot",
    name: "Double Tap",
    description: "Auto-cannon fires an extra projectile per volley.",
    tags: ["weapon"],
    rarity: "epic",
    stackable: true,
    maxStacks: 2,
    effect: { type: "weapon_mod", weaponTag: "auto", mods: { extraShotsAdd: 1 } },
  },
  {
    id: "projectile_speed_up",
    name: "High Velocity",
    description: "All projectiles travel 20% faster.",
    tags: ["weapon"],
    rarity: "common",
    stackable: true,
    maxStacks: 3,
    effect: { type: "weapon_mod", mods: { projectileSpeedMult: 1.2 } },
  },
  {
    id: "stall_grace_up",
    name: "Stall Grace",
    description: "Stall timer extended by 0.5 seconds.",
    tags: ["survival"],
    rarity: "rare",
    stackable: true,
    effect: { type: "stat_add", stat: "stallTime", amount: 0.5 },
  },
  {
    id: "boost_max_up",
    name: "Fuel Tank",
    description: "Boost capacity increased by 20.",
    tags: ["boost"],
    rarity: "common",
    stackable: true,
    effect: { type: "stat_add", stat: "boostMax", amount: 20 },
  },
  {
    id: "hp_max_up",
    name: "Hull Plating",
    description: "Maximum HP increased by 20.",
    tags: ["defense"],
    rarity: "common",
    stackable: true,
    effect: { type: "stat_add", stat: "hpMax", amount: 20 },
  },
  {
    id: "rear_blaster_unlock",
    name: "Rear Blaster",
    description: "Unlock a rear-facing weapon that fires behind you.",
    tags: ["weapon", "unlock"],
    rarity: "epic",
    stackable: false,
    effect: { type: "special", specialId: "unlock_rear_blaster" },
  },
];
